
[env:esp32c3]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32-c3-devkitm-1
framework = arduino
board_build.f_cpu = 160000000L
board_build.flash_mode = dio
board_build.filesystem = littlefs
monitor_speed = 115200
build_flags = 
	-D ESP32C3
	-I src

lib_deps = 
