// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Calendar1 = lv_calendar_create(ui_Screen1);
lv_obj_t *ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
lv_obj_set_width( ui_Calendar1, 230);
lv_obj_set_height( ui_Calendar1, 240);
lv_obj_set_x( ui_Calendar1, 5 );
lv_obj_set_y( ui_Calendar1, -3 );
lv_obj_set_align( ui_Calendar1, LV_ALIGN_CENTER );

ui_btn1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_btn1, 100);
lv_obj_set_height( ui_btn1, 50);
lv_obj_set_x( ui_btn1, -108 );
lv_obj_set_y( ui_btn1, -93 );
lv_obj_set_align( ui_btn1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btn1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -104 );
lv_obj_set_y( ui_Label1, -93 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"你好");
lv_obj_set_style_text_font(ui_Label1, &ui_font_Font2, LV_PART_MAIN| LV_STATE_DEFAULT);

}
