// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "../../App_Launcher/UI/ui_helpers.h"
#include "ui_events.h"

    // SCREEN: ui_ScreenTimer
    void ui_ScreenTimer_screen_init(void);
    extern lv_obj_t *ui_ScreenTimer;
    extern lv_obj_t *ui_Panel1;
    extern lv_obj_t *ui_TimeMs;
    extern lv_obj_t *ui_Label1;
    extern lv_obj_t *ui_Label2;
    extern lv_obj_t *ui_TimeMinSec;
    extern lv_obj_t *ui_Label4;
    extern lv_obj_t *ui_Label3;
    extern lv_obj_t *ui_Label5;
    extern lv_obj_t *ui_Label6;
    extern lv_obj_t *ui____initial_actions0;

    LV_FONT_DECLARE(ui_font_DSDIGIT64);
    LV_FONT_DECLARE(ui_font_DSDIGIT90);

    void xlap_ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
