; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
#upload_port = /dev/cu.usbmodem14301
build_unflags =
	-D ARDUINO_USB_MODE=1
build_flags =
	-D ESP32S3
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D APP_USB_VID=0x303A
	-D APP_USB_PID=0x0002
	-I src
lib_deps = 
	greiman/SdFat @ ^2.2.2

; extra_scripts = pre:native_usb_upload.py
	
